// Generated from zotero/translators metadata. Do not edit entries by hand.
export const ZOTERO_TRANSLATORS_COMMIT = '0c78a24a68896245248a68e4e5b9627b6f2d77fe';

export interface ZoteroScholarlyTarget {
  label: string;
  target: string;
}

export const ZOTERO_SCHOLARLY_TARGETS = [
  { label: "Access Engineering", target: "^https?://www\\.accessengineeringlibrary\\.com/" },
  { label: "Access Science", target: "^https?://www\\.accessscience\\.com/" },
  { label: "ACLWeb", target: "^https?://(www\\.)?(aclanthology\\.org|aclweb\\.org/anthology)/" },
  { label: "ACM Digital Library", target: "^https://dl\\.acm\\.org/(doi|do|profile|toc|topic|keyword|action/doSearch|acmbooks|browse)" },
  { label: "ACM Queue", target: "^https://queue\\.acm\\.org/" },
  { label: "ACS Publications", target: "^https?://pubs\\.acs\\.org/(toc/|journal/|topic/|isbn/\\d|doi/(full/|abs/|epdf/|book/)?10\\.|action/(doSearch\\?|showCitFormats\\?.*doi))" },
  { label: "AEA Web", target: "^https?://www\\.aeaweb\\.org/(articles|journals|issues)" },
  { label: "AGRIS", target: "^https?://agris\\.fao\\.org/agris-search/search" },
  { label: "AIP", target: "^https?://scitation\\.aip\\.org/(search\\?|content/)" },
  { label: "Airiti", target: "^https?://([^/]+\\.)?airitilibrary\\.com/Publication/alDetailedMesh" },
  { label: "American Institute of Aeronautics and Astronautics", target: "^https?://arc\\.aiaa\\.org/" },
  { label: "AMS Journals", target: "^https?://www\\.ams\\.org/journals/" },
  { label: "AMS MathSciNet", target: "^https?://mathscinet\\.ams\\.[^/]*/mathscinet/(article\\?|publications-search\\?|author\\?)" },
  { label: "AMS MathSciNet (Legacy)", target: "^https?://(mathscinet\\.)?ams\\.[^/]*/(mathscinet/2006/)?mathscinet(\\-getitem\\?|/search/(publications\\.html|publdoc\\.html))" },
  { label: "Annual Reviews", target: "^https?://[^/]*annualreviews\\.org(:[\\d]+)?(?=/)[^?]*(/(toc|journal|doi)/|showMost(Read|Cited)Articles|doSearch)" },
  { label: "APA PsycNet", target: "^https?://(psycnet|doi)\\.apa\\.org/" },
  { label: "APS", target: "^https?://journals\\.aps\\.org/([^/]+/(abstract|supplemental|references|cited-by|issues)/|search(\\?|/))" },
  { label: "APS-Physics", target: "^https?://(www\\.)?(physics)\\.aps\\.org/" },
  { label: "AquaDocs", target: "^https?://aquadocs\\.org/(handle|discover|browse)" },
  { label: "Archiv fuer Sozialgeschichte", target: "^https?://library\\.fes\\.de/jportal/" },
  { label: "Archive Ouverte en Sciences de l'Information et de la Communication  (AOSIC)", target: "^https?://archivesic\\.ccsd\\.cnrs\\.fr/" },
  { label: "arXiv.org", target: "^https?://([^\\.]+\\.)?(arxiv\\.org|xxx\\.lanl\\.gov)/(search|find|catchup|list/\\w|abs/|pdf/)" },
  { label: "ASCE", target: "^https?://(www\\.)?ascelibrary\\.org/(toc|doi|action)/" },
  { label: "ASCO Meeting Library", target: "^https?://meetinglibrary\\.asco\\.org/(content|search)" },
  { label: "ASTIS", target: "^https?://(www\\.)?aina\\.ucalgary\\.ca/" },
  { label: "ATS International Journal", target: "^https?://(www\\.)?atsinternationaljournal\\.com/" },
  { label: "Atypon Journals", target: "^https?://[^?#]+(/doi/((abs|abstract|full|figure|ref|citedby|book)/)?10\\.|/action/doSearch\\?)|^https?://[^/]+/toc/" },
  { label: "AustLII and NZLII", target: "^https?://(www\\d?|classic)\\.(austlii\\.edu\\.au|nzlii\\.org)" },
  { label: "Baidu Scholar", target: "^https?://(www\\.)?xueshu\\.baidu\\.com/" },
  { label: "beck-online", target: "^https?://beck[-.]online\\.beck\\.de/" },
  { label: "BioMed Central", target: "^https?://[^\\.]+\\.(biomedcentral|springeropen)\\.com/(articles|search)" },
  { label: "BioOne", target: "^https?://[^/]*www\\.bioone\\.org[^/]*/s" },
  { label: "BOFiP-Imp\u00f4ts", target: "^https?://bofip\\.impots\\.gouv\\.fr/bofip/" },
  { label: "Brill", target: "^https?://(www\\.|referenceworks\\.|bibliographies\\.)?brill(online)?\\.com/" },
  { label: "Bryn Mawr Classical Review", target: "^https?://bmcr\\.brynmawr\\.edu/" },
  { label: "Bundesgesetzblatt", target: "^https?://www\\.bgbl\\.de/" },
  { label: "CABI - CAB Abstracts", target: "^https?://(www\\.)?cabidirect\\.org/cabdirect" },
  { label: "Cairn.info", target: "^https?://www\\.cairn\\.info/" },
  { label: "Cambridge Core", target: "^https?://www\\.cambridge\\.org/core/(search\\?|journals/|books/|.+/listing?)" },
  { label: "Cambridge Engage Preprints", target: "/engage/[^/]+/(article-details/|search-dashboard\\?)" },
  { label: "CAOD", target: "^https?://caod\\.oriprobe\\.com/articles/" },
  { label: "Cascadilla Proceedings Project", target: "^https?://(www\\.)?lingref\\.com/" },
  { label: "Cell Press", target: "^https?://([^/]*\\.)?cell\\.com" },
  { label: "Central and Eastern European Online Library Journals", target: "^https?://www\\.ceeol\\.com/search" },
  { label: "CERN Document Server", target: "^https?://cds\\.cern\\.ch/(search\\?|collection/|record/)" },
  { label: "Chicago Journal of Theoretical Computer Science", target: "^https?://cjtcs\\.cs\\.uchicago\\.edu/articles" },
  { label: "CiNii Research", target: "^https?://cir\\.nii\\.ac\\.jp/" },
  { label: "CiteSeer", target: "^https?://citeseerx?\\.ist\\.psu\\.edu" },
  { label: "Citizen Lab", target: "^https?://citizenlab\\.ca/" },
  { label: "Climate Change and Human Health Literature Portal", target: "^https?://tools\\.niehs\\.nih\\.gov/cchhl/index\\.cfm" },
  { label: "clinicaltrials.gov", target: "^https://(classic\\.clinicaltrials\\.gov/ct2/(show|results)|(www\\.)?clinicaltrials\\.gov/(study|search))\\b" },
  { label: "CNKI", target: "^https?://([^/]+\\.)?cnki\\.net" },
  { label: "COBISS", target: "^https?://plus\\.cobiss\\.net/cobiss" },
  { label: "Code4Lib Journal", target: "^https?://journal\\.code4lib\\.org/" },
  { label: "Common-Place", target: "^https?://(www\\.)?(common-place\\.org/|common-place-archives\\.org/)" },
  { label: "Copernicus", target: "^https?://[^./]+\\.copernicus\\.org/" },
  { label: "CQ Press", target: "^https?://library\\.cqpress\\.com/" },
  { label: "CROSBI", target: "^https?://www\\.bib\\.irb\\.hr/" },
  { label: "CSIRO Publishing", target: "^https?://(www\\.)?publish\\.csiro\\.au/" },
  { label: "DABI", target: "^https?://dabi\\.ib\\.hu-berlin\\.de/" },
  { label: "Dagstuhl Research Online Publication Server", target: "^https?://(www\\.)?drops\\.dagstuhl\\.de/" },
  { label: "DAI-Zenon", target: "^https?://zenon\\.dainst\\.org/(Record/|Search/)" },
  { label: "Dar Almandumah", target: "^https?://search\\.mandumah\\.com/(Search|Record)/" },
  { label: "DART-Europe", target: "^https?://www\\.dart-europe\\.org" },
  { label: "Databrary", target: "^https?://nyu\\.databrary\\.org/(volume|search)" },
  { label: "Dataverse", target: "^https?://(www\\.)?((open|research-?|hei|planetary-|osna|in|bonn|borealis|lida\\.|archaeology\\.|entrepot\\.recherche\\.|archive\\.|redape\\.)?(data|e?da[td]os)|dvn|sodha\\.be|repositorio(\\.|dedados|pesquisas)|abacus\\.library\\.ubc\\.ca|dorel\\.univ-lorraine\\.fr|darus\\.uni-stuttgart\\.de|dunas\\.ua\\.pt|edmond\\.mpdl\\.mpg\\.de|keen\\.zih\\.tu-dresden\\.de|rdr\\.kuleuven\\.be|portal\\.odissei\\.nl)" },
  { label: "DBLP Computer Science Bibliography", target: "^https?://(www\\.)?(dblp\\d?(\\.org|\\.uni-trier\\.de/|\\.dagstuhl\\.de/))" },
  { label: "DBpia", target: "^https?://[^/]+\\.dbpia\\.co\\.kr/" },
  { label: "De Gruyter Brill", target: "^https?://www\\.degruyterbrill\\.com/" },
  { label: "Defense Technical Information Center", target: "^https?://oai\\.dtic\\.mil/oai/" },
  { label: "Delpher", target: "^https?://[^\\/]+\\.delpher\\.nl" },
  { label: "Demographic Research", target: "^https?://www\\.demographic-research\\.org" },
  { label: "Dialnet", target: "^https?://dialnet\\.unirioja\\.es/" },
  { label: "Digital Humanities Quarterly", target: "^https?://(www\\.)?digitalhumanities\\.org/(dhq)?" },
  { label: "DigiZeitschriften", target: "^https?://www\\.digizeitschriften\\.de/((en/)?dms/|index\\.php\\?id=27[24])" },
  { label: "Dimensions", target: "^https?://app\\.dimensions\\.ai/" },
  { label: "dLibra", target: "/.*dlibra/(doccontent|docmetadata|collectiondescription|results)|/dlibra/?" },
  { label: "DOAJ", target: "^https?://(www\\.)?doaj\\.org/(article|search)/" },
  { label: "Dryad Digital Repository", target: "^https?://(www\\.)?datadryad\\.org/" },
  { label: "E-periodica Switzerland", target: "^https?://(www|news?)\\.e-periodica\\.ch" },
  { label: "Electronic Colloquium on Computational Complexity", target: "^https?://eccc\\.weizmann\\.ac\\.il/(title|year|keyword|report|search)" },
  { label: "eLibrary.ru", target: "^https?://(www\\.)?elibrary\\.ru/" },
  { label: "eLife", target: "^https?://(elife\\.)?elifesciences\\.org/(articles|search|subjects|archive)" },
  { label: "Elsevier Health Journals", target: "/action/doSearch\\?|/article/[^/]+/(abstract|fulltext|references|images)" },
  { label: "Elsevier Pure", target: "/[a-z]{2}/(publications|persons|searchAll)/" },
  { label: "eMedicine", target: "^https?://emedicine\\.medscape\\.com/article/" },
  { label: "Emerald Insight", target: "^https?://www\\.emerald\\.com/insight/(publication/|content/|search\\?)" },
  { label: "eMJA", target: "^https?://www\\.mja\\.com\\.au/" },
  { label: "Envidat", target: "^https://(www\\.)?envidat.ch/" },
  { label: "EPA National Library Catalog", target: "^https?://cfpub\\.epa\\.gov/ols" },
  { label: "ePrint IACR", target: "^https://eprint\\.iacr\\.org/" },
  { label: "ERIC", target: "^https?://(www\\.)?eric\\.ed\\.gov/" },
  { label: "Erudit", target: "^https?://(www\\.)?erudit\\.org/" },
  { label: "etatar.ru", target: "^https?://(www\\.)?etatar\\.ru/" },
  { label: "Euclid", target: "^https?://[^/]*projecteuclid\\.org[^/]*/" },
  { label: "Europe PMC", target: "^https?://europepmc\\.org/" },
  { label: "F1000 Research", target: "^https?://(www\\.)?(((openresearchcentral|(aas|amrc|hrb|wellcome|gates)openresearch)\\.org)|(f1000research|emeraldopenresearch)\\.com)/" },
  { label: "Fachportal P\u00e4dagogik", target: "^https?://(www\\.fachportal-paedagogik\\.de/literatur/|www\\.pedocs\\.de/)" },
  { label: "FAO Knowledge Repository", target: "^https?://openknowledge\\.fao\\.org/(items/|search|browse/|collections/)" },
  { label: "Fatcat", target: "^https://fatcat\\.wiki/" },
  { label: "Frontiers", target: "^https?://[^./]+\\.frontiersin\\.org/" },
  { label: "Game Studies", target: "^https?://gamestudies\\.org/\\d" },
  { label: "Gasyrlar Awazy", target: "^https?://www\\.archive\\.gov\\.tatarstan\\.ru/magazine/go/anonymous/main/\\?path=mg:/" },
  { label: "GMS German Medical Science", target: "^https?://www\\.egms\\.de/static/(de|en)/" },
  { label: "Google Research", target: "^https://research\\.google/(pubs|people|research-areas|teams)" },
  { label: "Google Scholar", target: "^https?://scholar[-.]google[-.](com|cat|(com?[-.])?[a-z]{2})(\\.[^/]+)?/(scholar(_case|_labs/search/session/\\d+)?\\?|citations\\?)" },
  { label: "HAL", target: "^https://([^/.]+\\.)?hal\\.science/" },
  { label: "HCSP", target: "^https?://(www\\.)?hcsp\\.fr/explore\\.cgi/" },
  { label: "HeinOnline", target: "^https?://(www\\.)?heinonline\\.org/HOL/(LuceneSearch|Page|IFLPMetaData|AuthorProfile)\\?" },
  { label: "Herder", target: "^https?://www\\.herder\\.de/" },
  { label: "HighBeam", target: "^https?://www\\.highbeam\\.com/" },
  { label: "HighWire 2.0", target: "^[^?#]+(/content/([0-9.]+[A-Z\\-]*/|current|firstcite|early)|/search\\?.*?\\bsubmit=|/search(/results)?\\?fulltext=|/cgi/collection/.|/search/.)" },
  { label: "Hindawi Publishers", target: "^https?://www\\.hindawi\\.com/(journals|search)/" },
  { label: "Hispanic-American Periodical Index", target: "^https?://hapi\\.ucla\\.edu" },
  { label: "Homeland Security Digital Library", target: "^https?://www\\.hsdl\\.org/" },
  { label: "Human Rights Watch", target: "^https?://www\\.hrw\\.org/" },
  { label: "IBISWorld", target: "^https?://clients\\d\\.ibisworld\\.com/(reports|search)" },
  { label: "IEEE Computer Society", target: "^https?://(www[0-9]?|search[0-9]?)\\.computer\\.org/(csdl/(mags/[0-9a-z/]+|trans/[0-9a-z/]+|letters/[0-9a-z]+|proceedings/[0-9a-z/]+|doi|abs/proceedings)|search/results|portal/web/computingnow/.*content\\?)" },
  { label: "IEEE Xplore", target: "^https?://([^/]+\\.)?ieeexplore\\.ieee\\.org/([^#]+[&?]arnumber=\\d+|(abstract/)?document/|search/(searchresult|selected)\\.jsp|xpl/(mostRecentIssue|tocresult)\\.jsp\\?|xpl/conhome/\\d+/proceeding)" },
  { label: "IETF", target: "^https?://(datatracker\\.ietf\\.org/|www\\.ietf\\.org/archive/id/|tools\\.ietf\\.org/pdf/|www\\.rfc-editor\\.org/)" },
  { label: "Ined", target: "^https?://archined\\.ined\\.fr/" },
  { label: "Informationssystem Medienpaedagogik", target: "^https?://www\\.ism-info\\.de/ism-info\\.html\\?" },
  { label: "IngentaConnect", target: "^https?://(www\\.)?ingentaconnect\\.com" },
  { label: "INSPIRE", target: "^https?://inspirehep\\.net/" },
  { label: "Institute of Physics", target: "^https?://iopscience\\.iop\\.org/((article/10\\.[^/]+/)?[0-9-X]+/.+|n?search\\?.+)" },
  { label: "Inter-Research Science Center", target: "^https?://www\\.int-res\\.com/" },
  { label: "International Nuclear Information System", target: "^https?://inis\\.iaea\\.org/" },
  { label: "InvenioRDM", target: "^https?://(zenodo\\.org|sandbox\\.zenodo\\.org|data\\.caltech\\.edu|repository\\.tugraz\\.at|researchdata\\.tuwien\\.at|ultraviolet\\.library\\.nyu\\.edu|adc\\.ei-basel\\.hasdai\\.org|fdat\\.uni-tuebingen\\.de|www\\.fdr\\.uni-hamburg\\.de|rodare\\.hzdr\\.de|aperta\\.ulakbim.gov\\.tr|www\\.openaccessrepository\\.it|eic-zenodo\\.sdcc\\.bnl\\.gov)" },
  { label: "Isidore", target: "^https?://(www\\.)?isidore\\.science/" },
  { label: "J-Stage", target: "^https?://www\\.jstage\\.jst\\.go\\.jp/" },
  { label: "Jahrbuch", target: "^https?://www\\.emis\\.de/cgi-bin/jfmen/MATH/JFM/" },
  { label: "Journal of Electronic Publishing", target: "^https?://quod\\.lib\\.umich\\.edu/j/jep" },
  { label: "Journal of Extension", target: "^https?://www\\.joe\\.org/" },
  { label: "Journal of Machine Learning Research", target: "^https?://((www\\.)?(jmlr\\.(org|csail\\.mit\\.edu))/(papers/v|mloss/)|proceedings\\.mlr\\.press/v)" },
  { label: "JRC Publications Repository", target: "^https?://(www\\.)?publications\\.jrc\\.ec\\.europa\\.eu/repository/(handle/|simple-search\\?|browse\\?)" },
  { label: "JSTOR", target: "^https?://([^/]+\\.)?jstor\\.org/(discover/|action/(showArticle|doBasicSearch|doAdvancedSearch|doLocatorSearch|doAdvancedResults|doBasicResults)|stable/|pss/|openurl\\?|sici\\?)" },
  { label: "jurion", target: "^https?://www\\.recht\\.jurion\\.de/" },
  { label: "Juris", target: "^https?://(www\\.|testsystem\\.)?juris\\.de/" },
  { label: "JurPC", target: "^https?://www\\.jurpc\\.de/jurpc/show\\?id=" },
  { label: "KiM", target: "^https?://[^/]*kimnet\\.nl/document" },
  { label: "Korean National Library", target: "^https?://www\\.nl\\.go\\.kr/(EN|NL)/contents/(eng)?[sS]earch\\.do" },
  { label: "KStudy", target: "^https?://[^/]+\\.kstudy\\.com" },
  { label: "L'Ann\u00e9e Philologique", target: "^https?://cpps\\.brepolis\\.net/aph/" },
  { label: "Landesbibliographie Baden-W\u00fcrttemberg", target: "^https?://(www\\.)?(statistik\\.baden-wuerttemberg|statistik-bw)\\.de/LABI" },
  { label: "LexisNexis", target: "^https?://[^/]*lexis-?nexis\\.com" },
  { label: "Library Catalog (PICA)", target: "^https?://[^/]+(/[^/]+)*//?DB=\\d" },
  { label: "Library Catalog (RERO ILS)", target: "^https://((ils\\.test|bib)\\.rero\\.ch|ils\\.bib\\.uclouvain\\.be)/[^/]+/(documents/\\d+|search/documents\\?)" },
  { label: "Library Catalog (TIND ILS)", target: "/search.+p=|record/[0-9]+" },
  { label: "Library Catalog (Visual Library 2021)", target: "/search(/quick)?\\?|/nav/index/|/(content|periodical)/" },
  { label: "LingBuzz", target: "^https://(ling\\.auf|lingbuzz)\\.net/lingbuzz/(repo/semanticsArchive/article/)?(\\d+|_search)" },
  { label: "Lippincott Williams and Wilkins", target: "^https?://(www\\.)?journals\\.lww\\.com/" },
  { label: "LIVIVO", target: "^https?://www\\.livivo\\.de/" },
  { label: "LookUs", target: "/jvi.aspx[^#]*[?&](volume|issue|un)=" },
  { label: "magazines.russ.ru", target: "^https?://magazines\\.russ\\.ru/[a-zA-Z -_]+/[0-9]+/[0-9]+/" },
  { label: "MDPI Journals", target: "^https?://www\\.mdpi\\.com" },
  { label: "medes", target: "^https?://(www\\.)?medes\\.com/" },
  { label: "mEDRA", target: "^https?://www\\.medra\\.org/servlet/view\\?" },
  { label: "Microbiology Society Journals", target: "^https?://(www\\.)?(\\w)+\\.microbiologyresearch\\.org/(content/journal/|search?)" },
  { label: "Microsoft Academic", target: "^https?://academic\\.microsoft\\.com" },
  { label: "MIDAS Journals", target: "^https?://(www\\.)?(insight-journal|midasjournal|vtkjournal)\\.org/" },
  { label: "MPG PuRe", target: "^https?://pure\\.mpg\\.de/" },
  { label: "NASA ADS", target: "^(https://ui\\.adsabs\\.harvard\\.edu/(search|abs)/)|(^https://scixplorer\\.org/(search|abs/))" },
  { label: "NASA NTRS", target: "^https?://ntrs\\.nasa\\.gov/(citations/|search)" },
  { label: "National Agriculture Library", target: "^https?://(pubag|naldc)\\.nal\\.usda\\.gov/" },
  { label: "National Bureau of Economic Research", target: "^https?://(papers\\.|www2?\\.)?nber\\.org/(system/files/)?(papers|s|new|custom|books-and-chapters|chapters)" },
  { label: "National Diet Library Catalogue", target: "^https?://iss\\.ndl\\.go\\.jp/" },
  { label: "National Technical Reports Library", target: "^https?://ntrl\\.ntis\\.gov/NTRL/" },
  { label: "National Transportation Library ROSA P", target: "^https?://rosap\\.ntl\\.bts\\.gov/" },
  { label: "Nature Publishing Group", target: "^https?://(www\\.)?nature\\.com/([^?/]+/)?(journal|archive|research|topten|search|full|abs|current_issue\\.htm|most\\.htm|articles/)" },
  { label: "NCBI Nucleotide", target: "^https?://(www\\.)?ncbi\\.nlm\\.nih\\.gov/nuccore/" },
  { label: "Neural Information Processing Systems", target: "^https?://(papers|proceedings)\\.n(eur)?ips\\.cc/" },
  { label: "New Left Review", target: "^https?://(www\\.)?newleftreview\\.org/issues/" },
  { label: "Notre Dame Philosophical Reviews", target: "^https?://ndpr\\.nd\\.edu/" },
  { label: "NRC Research Press", target: "^https?://www\\.nrcresearchpress\\.com" },
  { label: "NTSB Accident Reports", target: "^https?://(www\\.)?ntsb\\.gov/investigations/AccidentReports/Pages/" },
  { label: "OECD", target: "^https?://(www\\.)?oecd-ilibrary\\.org/" },
  { label: "Open Knowledge Repository", target: "^https?://openknowledge\\.worldbank\\.org/" },
  { label: "Open WorldCat", target: "^https?://([^/]+\\.)?worldcat\\.org/" },
  { label: "OpenAlex", target: "^https://openalex\\.org/works" },
  { label: "OpenEdition Journals", target: "^https?://journals\\.openedition\\.org/" },
  { label: "Optical Society of America", target: "^https?://((www\\.)?osapublishing|opg\\.optica)\\.org" },
  { label: "Optimization Online", target: "^https?://optimization-online\\.org/" },
  { label: "OSF Preprints", target: "^https://osf\\.io/" },
  { label: "OSTI Energy Citations", target: "^https?://www\\.osti\\.gov/(energycitations|scitech)" },
  { label: "Ovid OCE", target: "^https://oce\\.ovid\\.com/" },
  { label: "Oxford Music and Art Online", target: "^https?://([^/]+\\.)?www\\.oxford(music|art)online\\.com/" },
  { label: "Papers Past", target: "^https?://(www\\.)?paperspast\\.natlib\\.govt\\.nz/" },
  { label: "Peeters", target: "^https?://(www\\.)?poj\\.peeters-leuven\\.be/content\\.php" },
  { label: "PEI Archival Information Network", target: "^https?://www\\.archives\\.pe\\.ca/atom/index\\.php/" },
  { label: "PEP Web", target: "^https?://www\\.pep-web\\.org" },
  { label: "Perceiving Systems", target: "^https?://ps\\.is\\.tuebingen\\.mpg\\.de/publications" },
  { label: "Philosopher's Imprint", target: "^https?://quod\\.lib\\.umich\\.edu/p/phimp" },
  { label: "PhilPapers", target: "^https?://phil(papers|archive)\\.org/" },
  { label: "PKP Catalog Systems", target: "/(article|preprint|issue)/view/|/catalog/book/|/search/search|/index\\.php/default" },
  { label: "PLoS Journals", target: "^https?://(www\\.plos(one|ntds|compbiol|pathogens|genetics|medicine|biology)\\.org|journals\\.plos\\.org(/\\w+)?)/(search|\\w+/article)" },
  { label: "Preprints.org", target: "^https://www\\.preprints\\.org/" },
  { label: "Project MUSE", target: "^https?://[^/]*muse\\.jhu\\.edu/(book/|pub/|article/|issue/|search\\?)" },
  { label: "ProQuest", target: "^https?://(www|search)\\.proquest\\.com/(.*/)?(docview|pagepdf|results|publicationissue|browseterms|browsetitles|browseresults|myresearch/(figtables|documents))" },
  { label: "ProQuest PolicyFile", target: "^https?://www\\.policyfile\\.com" },
  { label: "Protein Data Bank", target: "^https?://www\\.(pdb|rcsb)\\.org/pdb/" },
  { label: "PubFactory Journals", target: "^https://([^/]+/view/journals/.+\\.xml|[^.]*journals\\.[^/]+/search)\\b" },
  { label: "PubMed", target: "^https?://([^/]+\\.)?(www|preview)\\.ncbi\\.nlm\\.nih\\.gov[^/]*/(m/)?(books|pubmed|labs/pubmed|myncbi|sites/pubmed|sites/entrez|entrez/query\\.fcgi\\?.*db=PubMed|myncbi/browse/collection/?|myncbi/collections/)|^https?://pubmed\\.ncbi\\.nlm\\.nih\\.gov/(\\d|\\?|searches/|clipboard|collections/)" },
  { label: "PubMed Central", target: "^https://(www\\.)?(pmc\\.ncbi\\.nlm\\.nih\\.gov/|ncbi\\.nlm\\.nih\\.gov/pmc)" },
  { label: "PubPub", target: "/pub/[^/]+/release/\\d+|^https?://[^/]+\\.pubpub\\.org/search\\?" },
  { label: "Qatar Digital Library", target: "^https?://(www\\.)?qdl\\.qa/" },
  { label: "RAND", target: "^https://www\\.rand\\.org/(pubs/|search\\.html)" },
  { label: "REDALYC", target: "^https?://(www\\.)?redalyc\\.(uaemex\\.mx|org)" },
  { label: "RePEc - Econpapers", target: "^https?://econpapers\\.repec\\.org/" },
  { label: "RePEc - IDEAS", target: "^https?://ideas\\.repec\\.org/" },
  { label: "Research Square", target: "^https?://www\\.researchsquare\\.com/(article|browse)" },
  { label: "ResearchGate", target: "^https?://www\\.researchgate\\.net/" },
  { label: "RSC Publishing", target: "^https?://(:?www\\.|google\\.)?pubs\\.rsc\\.org/" },
  { label: "Russian State Library", target: "^https?://(search|favorites|aleph)\\.rsl\\.ru/" },
  { label: "SAE Papers", target: "^https?://(www|papers)\\.sae\\.org/" },
  { label: "SAGE Journals", target: "^https?://journals\\.sagepub\\.com(/doi/((abs|full|pdf)/)?10\\.|/action/doSearch\\?|/toc/)" },
  { label: "Scholars Portal Journals", target: "^https?://journals\\.scholarsportal\\.info/" },
  { label: "Scholia", target: "^https?://scholia\\.toolforge\\.org/work/Q" },
  { label: "SciELO", target: "^https?://(www\\.)?(socialscience\\.|proceedings\\.|biodiversidade\\.|caribbean\\.|comciencia\\.|inovacao\\.|search\\.)?(scielo|scielosp)\\." },
  { label: "ScienceDirect", target: "^https?://[^/]*science-?direct\\.com[^/]*/((science/)?(article/|(journal|bookseries|book|handbook)/\\d)|search[?/]|journal/[^/]+/vol)" },
  { label: "scinapse", target: "^https?://(www\\.)?scinapse\\.io/" },
  { label: "Scopus", target: "^https?://www\\.scopus\\.com/" },
  { label: "Semantic Scholar", target: "^https?://(www\\.semanticscholar\\.org/(paper/.+|search\\?|reader/.+)|pdfs\\.semanticscholar\\.org/)" },
  { label: "semantics Visual Library", target: "^https?://www\\.(blldb-online\\.de/blldb|bdsl-online\\.de/BDSL-DB)/suche/" },
  { label: "SFU IPinCH", target: "^https?://[^/]*sfu\\.ca/kbipinch/(records|browse|search)/" },
  { label: "Silverchair", target: "/(article|fullarticle|advance-article|advance-article-abstract|article-abstract|book|edited-volume)(/|\\.aspx)|search-results?|\\/issue(/|s\\.aspx|$)" },
  { label: "SIPRI", target: "^https?://(www\\.)?sipri\\.org/" },
  { label: "SLUB Dresden", target: "^https://katalog\\.slub-dresden\\.de/" },
  { label: "SORA", target: "^https?://sora\\.unm\\.edu/(node/|search/node/|advancedsearch\\?)" },
  { label: "Springer Link", target: "^https?://link\\.springer\\.com/(search(/page/\\d+)?\\?|(article|chapter|book|referenceworkentry|protocol|journal|referencework)/.+)" },
  { label: "SSOAR", target: "^https?://www\\.ssoar\\.info/" },
  { label: "SSRN", target: "^https?://(www|papers|hq)\\.ssrn\\.com/" },
  { label: "Superlib", target: "^https?://(book|jour)\\.ucdrs\\.superlib\\.net/(search|views/specific)" },
  { label: "Talis Aspire", target: "^https?://([^/]+\\.)?(((my)?reading|resource|lib|cyprus|)lists|aspire\\.surrey|rl\\.talis)\\..+/(lists|items)/" },
  { label: "Taylor and Francis+NEJM", target: "^https?://(www\\.)?(tandfonline\\.com|nejm\\.org)/" },
  { label: "Tesis Doctorals en Xarxa", target: "^https?://(www\\.)?(tdx\\.cat|tesisenred\\.net)" },
  { label: "The Microfinance Gateway", target: "^https?://(www\\.)?microfinancegateway\\.org/" },
  { label: "Theory of Computing", target: "^https?://(theoryofcomputing\\.org|toc\\.cse\\.iitk\\.ac\\.in|www\\.cims\\.nyu\\.edu/~regev/toc|toc\\.ilab\\.sztaki\\.hu|toc\\.nada\\.kth\\.se|tocmirror\\.cs\\.tau\\.ac\\.il)/articles/[vg].*(/|html?)$" },
  { label: "ThesesFR", target: "^https?://(www\\.)?theses\\.fr/([a-z]{2}/)?((s\\d+|\\d{4}.{8}|\\d{8}X|\\d{9})(?!\\.(rdf|xml)$)|resultats)" },
  { label: "Thieme", target: "^https?://(www\\.)?thieme-connect\\.com/products/" },
  { label: "Tony Blair Institute for Global Change", target: "^https://institute\\.global/" },
  { label: "Transportation Research Board", target: "^https?://(www|trid)\\.trb\\.org/" },
  { label: "Treesearch", target: "^https?://([^/]+\\.)?treesearch\\.fs\\.fed\\.us/(pubs/\\d+$|search\\.php)" },
  { label: "Ubiquity Journals", target: "^https?://[^/]+(/articles/10\\.\\d{4,9}/[-._;()/:a-z0-9A-Z]+|/articles/?$|/\\d+/volume/\\d+/issue/\\d+)" },
  { label: "UChicago VuFind", target: "^https?://([^/]+\\.)?lib\\.uchicago\\.edu/" },
  { label: "UPCommons", target: "^https?://upcommons\\.upc\\.edu" },
  { label: "UpToDate References", target: "^https?://www\\.uptodate\\.com/contents/" },
  { label: "USENIX", target: "^https://www\\.usenix\\.org/conference/.*/presentation" },
  { label: "Verniana-Jules Verne Studies", target: "^https?://[^/]*verniana\\.org(:\\d+)?/volumes/\\d+/" },
  { label: "Wanfang Data", target: "^https?://[ds]\\.(g\\.)?wanfangdata\\.com\\.cn" },
  { label: "Web of Science Nextgen", target: "^https://(www\\.webofscience\\.com|webofscience\\.clarivate\\.cn)/" },
  { label: "WHO", target: "^https?://apps\\.who\\.int/iris/" },
  { label: "Wikidata", target: "^https?://(www\\.)?wikidata\\.org/wiki/Q" },
  { label: "WikiLeaks PlusD", target: "^https?://(search\\.|www\\.)?wikileaks\\.org/plusd/" },
  { label: "Wildlife Biology in Practice", target: "^https?://[^/]*socpvs\\.org/journals/index\\.php/wbp" },
  { label: "Wiley Online Library", target: "^https?://([\\w-]+\\.)?onlinelibrary\\.wiley\\.com[^/]*/(book|doi|toc|advanced/search|search-web/cochrane|cochranelibrary/search|o/cochrane/(clcentral|cldare|clcmr|clhta|cleed|clabout)/articles/.+/sect0\\.html)" },
  { label: "wiso", target: "^https?://www\\.wiso-net\\.de/(document/|dosearch\\?)" },
  { label: "World History Connected", target: "worldhistoryconnected\\.press|historycooperative.*/whc/" },
  { label: "World Shakespeare Bibliography Online", target: "^https?://(www\\.)?worldshakesbib\\.org" },
  { label: "WorldCat Discovery Service", target: "^https?://[^/]+\\.worldcat\\.org/" },
  { label: "zbMATH", target: "^https?://(www\\.)?zbmath\\.org/" },
  { label: "ZIPonline", target: "^https?://(www)?\\.zip-online\\.de/" },
  { label: "ZOBODAT", target: "^https?://(www\\.)?zobodat\\.at/" },
  { label: "zotero.org", target: "^https?://[^/]*zotero\\.org(:\\d+)?/.+/(items|collections|library|publications|trash|search|item-list|item-details)(/|$)" },
] as const satisfies readonly ZoteroScholarlyTarget[];

type CompiledZoteroScholarlyTarget = { label: string; pattern: RegExp };

const ZOTERO_SCHOLARLY_TARGET_REGEXES: CompiledZoteroScholarlyTarget[] = [];

for (const entry of ZOTERO_SCHOLARLY_TARGETS) {
  try {
    ZOTERO_SCHOLARLY_TARGET_REGEXES.push({ label: entry.label, pattern: new RegExp(entry.target) });
  } catch {
    // Ignore translator targets that are not supported by the browser RegExp engine.
  }
}

export function matchesZoteroScholarlyTarget(url: string): boolean {
  return ZOTERO_SCHOLARLY_TARGET_REGEXES.some(({ pattern }) => pattern.test(url));
}
