[project]
name = "paperlens-server"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "asyncpg>=0.30.0",
    "certifi>=2026.4.22",
    "elasticsearch>=9.4.0",
    "fastapi>=0.115.0",
    "httpx>=0.28.1",
    "mos",
    "python-dotenv>=1.2.2",
    "redis[asyncio]>=5.0.0",
    "uvicorn[standard]>=0.30.6",
]

[tool.uv.sources]
mos = { path = "mos-1.5.3-py3-none-any.whl" }
